
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 18m01acs031
 */
public class StudentSystem extends javax.swing.JFrame {

    /**
     * Creates new form StudentSystem
     */
    DbConnection conn = new DbConnection();
    public StudentSystem() {
        initComponents();
        showTime();
        showDate();
          Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        GenderStudent = new javax.swing.JTextField();
        CourseStudent = new javax.swing.JTextField();
        StudentIdStudent = new javax.swing.JTextField();
        FirstNameStudent = new javax.swing.JTextField();
        LastNameStudent = new javax.swing.JTextField();
        RegisterBiography = new javax.swing.JButton();
        RetiriveBiography = new javax.swing.JButton();
        DeleteBiography = new javax.swing.JButton();
        UpdateBiography = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        BirthDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        RetrieveBiography = new javax.swing.JButton();
        LogOut1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel16.setFont(new java.awt.Font("Engravers MT", 1, 30)); // NOI18N
        jLabel16.setText("STUDENT MANAGEMENT SYSTEM");

        TimeLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        TimeLabel.setText("Time");

        DateLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        DateLabel.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Firstname");

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date of birth");

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Id");

        jLabel7.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lastname");

        GenderStudent.setForeground(new java.awt.Color(4, 4, 155));

        CourseStudent.setForeground(new java.awt.Color(4, 4, 155));

        StudentIdStudent.setForeground(new java.awt.Color(4, 4, 155));
        StudentIdStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIdStudentActionPerformed(evt);
            }
        });

        FirstNameStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameStudentActionPerformed(evt);
            }
        });

        LastNameStudent.setForeground(new java.awt.Color(4, 4, 155));

        RegisterBiography.setBackground(new java.awt.Color(4, 4, 155));
        RegisterBiography.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        RegisterBiography.setForeground(java.awt.Color.white);
        RegisterBiography.setText("Register");
        RegisterBiography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBiographyActionPerformed(evt);
            }
        });

        RetiriveBiography.setBackground(new java.awt.Color(4, 4, 155));
        RetiriveBiography.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        RetiriveBiography.setForeground(new java.awt.Color(255, 255, 255));
        RetiriveBiography.setText("Retrieve");
        RetiriveBiography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetiriveBiographyActionPerformed(evt);
            }
        });

        DeleteBiography.setBackground(new java.awt.Color(4, 4, 155));
        DeleteBiography.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        DeleteBiography.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBiography.setText("Delete");
        DeleteBiography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBiographyActionPerformed(evt);
            }
        });

        UpdateBiography.setBackground(new java.awt.Color(4, 4, 155));
        UpdateBiography.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        UpdateBiography.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBiography.setText("Update");
        UpdateBiography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBiographyActionPerformed(evt);
            }
        });

        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-export-40.png"))); // NOI18N
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        jLabel17.setText("Log out");

        BirthDateChooser.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Course name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FirstNameStudent)
                                    .addComponent(LastNameStudent)
                                    .addComponent(StudentIdStudent)
                                    .addComponent(GenderStudent)
                                    .addComponent(BirthDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(CourseStudent))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addComponent(RegisterBiography, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UpdateBiography, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(265, 265, 265)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DeleteBiography, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RetiriveBiography, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                        .addGap(9, 9, 9)))
                .addGap(350, 350, 350))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentIdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBiography, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterBiography, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RetiriveBiography, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBiography, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Register Student", jPanel4);

        jPanel3.setBackground(new java.awt.Color(4, 4, 155));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FIRSTNAME", "LASTNAME", "STUDENT ID", "GENDER", "DATE OF BIRTH", "COURSE NAME"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("BIOGRAPHY REPORT");

        RetrieveBiography.setBackground(new java.awt.Color(4, 4, 155));
        RetrieveBiography.setForeground(new java.awt.Color(255, 255, 255));
        RetrieveBiography.setText("RETRIEVE");
        RetrieveBiography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrieveBiographyActionPerformed(evt);
            }
        });

        LogOut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-export-40.png"))); // NOI18N
        LogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Log out");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RetrieveBiography)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogOut1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(RetrieveBiography)
                .addGap(189, 189, 189)
                .addComponent(LogOut1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        jTabbedPane1.addTab("Registration Report", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut1ActionPerformed
        // TODO add your handling code here:
        LogInForm logout = new LogInForm();
        dispose();
        logout.setVisible(true);
    }//GEN-LAST:event_LogOut1ActionPerformed

    private void RetrieveBiographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrieveBiographyActionPerformed
        // TODO add your handling code here:
        ResultSet newrs=conn.getStudentsBiography();
        try{
            DefaultTableModel newmodel=(DefaultTableModel)jTable2.getModel();
            while(newrs.next()){
                Vector<String>studentitems=new Vector<String>();
                studentitems.add(newrs.getString("firstname"));
                studentitems.add(newrs.getString("lastname"));
                studentitems.add(newrs.getString("studentid"));
                studentitems.add(newrs.getString("gender"));
                studentitems.add(newrs.getString("birthdate"));
                studentitems.add(newrs.getString("coursename"));
                newmodel.addRow(studentitems);
                new SimpleReport(newmodel);
            }
        }
        catch(SQLException x){
            JOptionPane.showMessageDialog(null, x.getMessage());
        }
    }//GEN-LAST:event_RetrieveBiographyActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        LogInForm logout = new LogInForm();
        dispose();
        logout.setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    private void UpdateBiographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBiographyActionPerformed
        // TODO add your handling code here:

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String fname=FirstNameStudent.getText();
        String lname=LastNameStudent.getText();
        String sid=StudentIdStudent.getText();
        String gender=GenderStudent.getText();
        String birthdate=dateFormat.format(BirthDateChooser.getDate());
        String coursename=CourseStudent.getText();
        conn.UpdateStudentBiography(fname, lname, sid,gender,birthdate,coursename);
    }//GEN-LAST:event_UpdateBiographyActionPerformed

    private void DeleteBiographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBiographyActionPerformed
        // TODO add your handling code here:

        String StudentId=StudentIdStudent.getText();

        conn.deleteStudentBiography(StudentId);
    }//GEN-LAST:event_DeleteBiographyActionPerformed

    private void RetiriveBiographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetiriveBiographyActionPerformed
        // TODO add your handling code here:
        ResultSet newrs=conn.getStudentsBiography();
        try{
            DefaultTableModel newmodel=(DefaultTableModel)jTable2.getModel();
            while(newrs.next()){
                Vector<String>studentitems=new Vector<String>();
                studentitems.add(newrs.getString("firstname"));
                studentitems.add(newrs.getString("lastname"));
                studentitems.add(newrs.getString("studentid"));
                studentitems.add(newrs.getString("gender"));
                studentitems.add(newrs.getString("birthdate"));
                studentitems.add(newrs.getString("coursename"));
                newmodel.addRow(studentitems);
            }
        }
        catch(SQLException x){
            JOptionPane.showMessageDialog(null, x.getMessage());
        }
    }//GEN-LAST:event_RetiriveBiographyActionPerformed

    private void RegisterBiographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBiographyActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String Fname=FirstNameStudent.getText();
        String Lname=LastNameStudent.getText();
        String Sid=StudentIdStudent.getText();
        String Gender=GenderStudent.getText();
        String Birthdate=dateFormat.format(BirthDateChooser.getDate());
        String Coursename=CourseStudent.getText();
        conn.insertStudentBiography(Fname, Lname, Sid,Gender,Birthdate,Coursename);
    }//GEN-LAST:event_RegisterBiographyActionPerformed

    private void FirstNameStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameStudentActionPerformed

    private void StudentIdStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIdStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIdStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSystem().setVisible(true);
            }
        });
    }
    public void showTime(){
        new Timer(0,new ActionListener(){
        
        @Override
        
        public void actionPerformed(ActionEvent e){
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("hh:MM:ss a");
        TimeLabel.setText(dateFormat.format(date));
        }
        }).start();
        
    }
     public void showDate(){
     Date date = new Date();
     SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        DateLabel.setText(dateFormat.format(date));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser BirthDateChooser;
    private javax.swing.JTextField CourseStudent;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton DeleteBiography;
    private javax.swing.JTextField FirstNameStudent;
    private javax.swing.JTextField GenderStudent;
    private javax.swing.JTextField LastNameStudent;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton LogOut1;
    private javax.swing.JButton RegisterBiography;
    private javax.swing.JButton RetiriveBiography;
    private javax.swing.JButton RetrieveBiography;
    private javax.swing.JTextField StudentIdStudent;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton UpdateBiography;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
